### ISSUE TITLE
来个可以动态生成二维码的功能（x）

### ISSUE THREAD

**Issue by djkcyl** [SakuraKoi/DgLabUnlocker#1]
别问咱为啥需要这种功能（）

目前已知的情况是游客登录的情况下，二维码会和账号登录的不一样

**Comment by SakuraKoi** [comment]
二维码似乎和账号绑定, 是否存在由客户端进行重置的可能性需要进一步逆向分析相关代码

**Comment by SakuraKoi** [comment]
二维码的实际参数为登录用户的uuid 不可重置
一次性远程口令密码有输入窗口, 但没有生成功能
发现一个"远程控制二维码是否可多次使用", 需进一步分析

**Comment by djkcyl** [comment]
目前我的方法是直接清除app数据，然后二维码就变了

**Comment by SakuraKoi** [comment]
> 目前我的方法是直接清除app数据，然后二维码就变了
草, 咱去看看私有存储底下是不是把uuid存那了

**Comment by SakuraKoi** [comment]
测试修改uuid无效, 应该是每次登录都会下发新的uuid和token

**Comment by SakuraKoi** [comment]
备忘:
游客登录数据hook点 before `com.bjsm.dungeonlab.d.n` `b(String object)`

**Comment by SakuraKoi** [comment]
该功能具有实现可行性, 加入功能计划

游客登录为收集一系列设备信息并拼装字符串, 哈希后传到服务器上, 响应uuid及token
实现方式暂定为hook游客登录数据并返回随机值, 以此实现游客登录每次都是不同的二维码

> 备忘: 游客登录数据hook点 before `com.bjsm.dungeonlab.d.n` `b(String object)`

**Comment by SakuraKoi** [comment]
spoof了数据但还是相同的二维码, 需要进一步研究

**Comment by djkcyl** [comment]
> spoof了数据但还是相同的二维码, 需要进一步研究

大佬加油，孩子不想再变成公交车了（x）

**Comment by SakuraKoi** [comment]
> > spoof了数据但还是相同的二维码, 需要进一步研究
> 
> 大佬加油，孩子不想再变成公交车了（x）

!?!?!?!??!??!????
<strike>你不对劲.jpg</strike>

**Comment by djkcyl** [comment]
> !?!?!?!??!??!???? 你不对劲.jpg

二维码发在群里，然后（x

**Comment by yywdddd** [comment]
游客似乎可以登录了 新版本可以每次重开清理账户数据（？

**Comment by yywdddd** [comment]
> > !?!?!?!??!??!???? 你不对劲.jpg
> 
> ~二维码发在群里，然后（x~

不对劲

**Comment by FishMagic** [comment]
远程连接时，固定使用账号UUID+2020作为连接云信的账号，而云信的账号需要通过DGLAB的后端注册，前端无法修改/新增，因此目前除了更换账号，没有作废原二维码的方式。。

**Comment by SakuraKoi** [comment]
> 远程连接时，固定使用账号UUID+2020作为连接云信的账号，而云信的账号需要通过DGLAB的后端注册，前端无法修改/新增，因此目前除了更换账号，没有作废原二维码的方式。。
> 
> **但是在双端建立连接时的报文中会包含一个pwd字段，理论上可以通过这个字段判断连接是否经过授权** **使用该方法时会要求双端均使用模块才可正确建立连接**

新版本中游客不登录也可以获取二维码, 经清除APP数据证实可以获得不同的游客账号, 目前研究的方向是伪造该流程中的关键数据以获取不同的游客UUID实现刷新二维码

**Comment by SakuraKoi** [comment]
> 这个功能要是被滥用，DGLAB那边估计可能会过来干掉你 
>（云信是按每月最高日活数量计费的

(危
草, 那还是算了
整活归整活, 涉及计费就太过分了

**Comment by djkcyl** [comment]
草，那没事了（）
