### ISSUE TITLE
直接输入设置强度

### ISSUE THREAD

**Issue by Rbqwow** [SakuraKoi/DgLabUnlocker#17]
aa就是可以手动输入之类的那种
+-好慢哦(bushi
(以及这边备用机也是a7.0 :/

**Comment by SakuraKoi** [comment]
!????? 你怎么也在玩这个
码发咱! (bushi

**Comment by Rbqwow** [comment]
昨天下午刚到手的 晚上已经被备用机的蓝牙搞麻了
不是经常断连就是延迟超高
以及 远程强度翻倍 官方还是没修 已经痛哭了
然后因为延迟超高按主机按钮都停不下来(悲

**Comment by SakuraKoi** [comment]
放弃当前1.3.2版本支持, 准备上手beta
