### ISSUE TITLE
rpc的加减强度好像有问题

### ISSUE THREAD

**Issue by djkcyl** [SakuraKoi/DgLabUnlocker#22]
app显示的数值变了，但实际上郊狼出来的强度不会变（

**Comment by SakuraKoi** [comment]
偶发还是稳定出现qw?
偶发有可能是多线程同步问题, 考虑加个hook把波形改动扔到decode前处理

**Comment by djkcyl** [comment]
> 偶发还是稳定出现qw? 偶发有可能是多线程同步问题, 考虑加个hook把波形改动扔到decode前处理

目前情况下是稳定复现

**Comment by SakuraKoi** [comment]
唔...稳定复现那咱回头拿自己做个实验看看...
开了别的什么功能么?

**Comment by djkcyl** [comment]
> 唔...稳定复现那咱回头拿自己做个实验看看... 开了别的什么功能么?

别的功能么，，（都开了）

**Comment by mis1042** [comment]
实测不行，显示强度增加实际输出一点没变，1.3.2

**Comment by SakuraKoi** [comment]
放弃当前1.3.2版本支持, 准备上手beta, 可预期即将到来一波大规模重构
