### ISSUE TITLE
连接时间计时器

### ISSUE THREAD

**Issue by huige233** [SakuraKoi/DgLabUnlocker#30]
用于统计玩的时间，可以简单通过一个starttime和endtime的时间戳判断，在断开时候显示

**Comment by SakuraKoi** [comment]
~~懒，不想写~~

**Comment by huige233** [comment]
> ~懒，不想写~

懒得你！

**Comment by huige233** [comment]
> > > ~懒，不想写~
> > 
> > 
> > 懒得你！
> 
> 怎么了! (叉腰

捏捏
