### ISSUE TITLE
一个大胆的想法：告别摸鱼！

### ISSUE THREAD

**Issue by xhz2** [SakuraKoi/DgLabUnlocker#37]
监测手环心率，如果手环心率不达标，就来点惩罚，不知道是否可行（逃~
比如小米手环 https://github.com/wuhan005/mebeats

还可以记录app使用时间，只允许每一小时玩15分钟手机呢（

虽然真的不会太多代码相关，但没有主人，自律又差，又要考试减肥健身抖m 自我感觉想法实在是太赞了，不提个issue有点亏，而且图书馆带郊狼瑟瑟想想就（（
这玩意不比keep、番茄学习之类的见效快欸嘿嘿嘿~~~

**Comment by SakuraKoi** [comment]
手环侧不太了解, 通过某种方式采集到手环心率等数据之后可以通过本模块的WebsocketRPC接口调整强度
