### ISSUE TITLE
模块设置替换失败

### ISSUE THREAD

**Issue by KasuganoHaruku** [SakuraKoi/DgLabUnlocker#39]
打开郊狼App可以看到unlocker选项，但点击unlocker设置时提示模块设置替换失败

已尝试重新安装LSposed，重新加载模块，重新安装DGLab软件，均未能解决问题

手机型号：OnePlus 6T A6013
安卓版本：11
DG-Lab版本：V1.3.3
LSPosed版本：1.8.6(6712)-Riru
魔改模块版本：1.9

问题截图：
![Screenshot_20230301-082055.jpg](https://user-images.githubusercontent.com/80110665/222013578-cced3d20-e9b2-4e9f-a975-6d719e228054.jpg)

启用模块时的日志（请原谅手机问题无法拷贝日志文件）
![Screenshot_20230301-083454.jpg](https://user-images.githubusercontent.com/80110665/222015076-ddf0a03b-5c58-4277-8949-72bcd840e341.jpg)

![Screenshot_20230301-083504.jpg](https://user-images.githubusercontent.com/80110665/222015086-4911b114-f272-41b2-97c5-d92c10b821bf.jpg)

**Comment by KasuganoHaruku** [comment]
问题已解决，回退到1.3.2版本后模块正常使用![Screenshot_20230301-084415.jpg](https://user-images.githubusercontent.com/80110665/222016106-86deb7dc-666c-4977-8dd2-a8e843d70259.jpg)

**Comment by SakuraKoi** [comment]
1.3.3暂不支持, app换了个新加固壳, 懒癌晚期不想动quq (又不是不能用.jpg
