### ISSUE TITLE
无视远程最大强度限制功能

### ISSUE THREAD

**Issue by YuuLuo** [SakuraKoi/DgLabUnlocker#41]
对方在上限设置为30时启用此功能，主控这里调到30以上会显示为橙色，但是被控端无变化

**Comment by SakuraKoi** [comment]
双方app版本?

**Comment by YuuLuo** [comment]
> 双方app版本?

主控端1.3.2 被控1.3.3 因为没法用模块
需要双方版本同步才可以嘛？还是说被控端也要使用模块

**Comment by SakuraKoi** [comment]
1.3.3可能对主控端强度数据增加了校验 导致绕过限制失效 
(未验证, 只是猜测
最近没空也没心情折腾1.3.3的那个易盾壳子, 先用着1.3.2吧

**Comment by SakuraKoi** [comment]
1.3.3可能对主控端强度数据增加了校验 导致绕过限制失效 
(未验证, 只是猜测
最近没空也没心情折腾1.3.3的那个易盾壳子, 先用着1.3.2吧
